version: '3'
services:
  flasky:
    build: .
    ports:
      - "80:5000"
    env_file: .env
    restart: always
    links:
      - mysql:dbserver
    volumes:
      - data:/home/flasky/data
      - modelsaves:/home/flasky/modelsaves
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql